version: '3'

services:
    redis:
        image: bitnami/redis
        ports:
            - 6379:6379
        environment:
            REDIS_PASSWORD: 'password'
    gateway:
        image: node:latest
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ./gateway:/home/node/app
        ports:
            - 3000:3000
        command: "yarn start"
        depends_on:
            - redis
    front-app:
        image: node:latest
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ./front-app:/home/node/app
        ports:
            - 3001:3000
        command: "yarn start"
        depends_on:
            - gateway
